### ISSUE TITLE
CTF 

### ISSUE THREAD

**Issue by PC-02** [HWTechClub/Roadmap#5]
Please fill out the details below.

### First and Last Name
Pranav Chachara
Akilan Selvacoumar

### Email

pc59@hw.ac.uk
as251@hw.ac.uk

### Company/Organization (Ex: Heriot-Watt) 

Heriot-Watt

### Job Title (Ex: Student)
Ethical Hacking Director
Tech Club President

### Project Title 
CTF

### Briefly describe the project
a Capture The Flag competition, designed to practice basic Linux skills.

### What kind of machines and how many do you expect to use?
VPS 

### What operating system and networking are you planning to use?
Linux
Apache

### Any other relevant details we should know about?
Will be hosted on Digital Ocean.

**Additional context**
-

**Comment by Akilan1999** [comment]
Will look into it
